blank_issues_enabled: true
contact_links:
  - name: Request programming help with coding challenges
    url: https://forum.freecodecamp.org
    about: Please visit this page for general support and programming help on coding challenges.
